name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v1
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          export NODE_ENV=production
          yarn
          yarn build
          yarn next export
      - name: Deploy to Surge
        run: |
          npm i -g surge
          surge ./out ${{ secrets.SURGE_DOMAIN }} --domain shaderday.com --token ${{ secrets.SURGE_TOKEN }}
      - name: Deploy GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
